version: '2'
services:
  nginx:
    image: library/nginx:1.23.2-alpine
    container_name: bowie-container-nginx
    restart: always
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    volumes:
      - ./public:/var/www/public
      - ./nginx.develop.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 22777:22777
    depends_on:
      - app
  app:
    build:
      context: .
    command: /usr/local/sbin/php-fpm
    container_name: bowie-container-app
    restart: always
    volumes:
      - .:/var/www/default:rw
    depends_on:
      - pgsql
      - redis
  pgsql:
    image: docker.io/library/postgres:14.6-alpine
    container_name: bowie-container-pgsql
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: library/redis:7.0.5-alpine
    command: redis-server --maxmemory-policy volatile-ttl --loglevel warning
    container_name: bowie-container-redis
    restart: always
    volumes:
      - redis-data:/data
volumes:
  pg-data:
  redis-data:
